{
 "title": "Tines Automation",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New Employees",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT eventId FROM \"tines_joiners\" WHERE eventType = 'user.lifecycle.create'"
    }
   ]
  },
  {
   "title": "Employees Changes",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT eventId FROM \"tines_movers\"  WHERE eventType = 'group.user_membership.add' OR eventType = 'group.user_membership.remove'"
    }
   ]
  },
  {
   "title": "Departed Employees",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT eventId FROM \"tines_leavers\" WHERE eventType = 'user.lifecycle.deactivate'"
    }
   ]
  },
  { "title": "Joiner Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT eventType,\"timestamp\"  from tines_joiners"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT eventType,username,displayName,title,department,team,groupChange,profileChange,\"timestamp\" FROM tines_joiners "
    }
   ]
  },
  { "title": "Mover Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT eventType,\"timestamp\"  from tines_movers"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT eventType,username,displayName,title,department,team,groupChange,profileChange,\"timestamp\" FROM \"tines_movers\""
    }
   ]
  },
  { "title": "Leaver Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT eventType,\"timestamp\"  from tines_leavers"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT eventType,username,displayName,title,department,team,groupChange,profileChange,\"timestamp\" FROM \"tines_leavers\""
    }
   ]
  }
 ]
}